### ISSUE TITLE
panic: open /var/log/web-history.log: permission denied

### ISSUE THREAD

**Issue by gedw99** [history-engine/engine#4]
I just pulled the code and ran make

looks like is assumes the log folder ?

```sh


# setup config.
cp example.setting.toml setting.toml

./history-engine-darwin-arm64
{"level":"debug","time":"2024-05-27T19:43:10+10:00","message":"open .env: no such file or directory"}
panic: open /var/log/web-history.log: permission denied

goroutine 1 [running]:
history-engine/engine/setting.checkFileExist()
        history-engine/engine/setting/log.go:30 +0x70
history-engine/engine/setting.loadLogger()
        history-engine/engine/setting/log.go:21 +0xc0
history-engine/engine/setting.Load({0x1034cff7e?, 0x1034c78b0?})
        history-engine/engine/setting/setting.go:19 +0x38
main.loadSetting(0x1400060f840?)
        history-engine/engine/main.go:46 +0x60
github.com/urfave/cli/v2.(*Command).Run(0x140000d2160, 0x1400060f840, {0x14000030180, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.27.1/command.go:219 +0x3d0
github.com/urfave/cli/v2.(*App).RunContext(0x14000636400, {0x10378c2f8, 0x103ccd460}, {0x14000030180, 0x1, 0x1})
        github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x514
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
        history-engine/engine/main.go:34 +0x334
```

Probably best to extend the Makefile to setup a runnable system in the Releases folder

Also add a Procfile and use runner to run both things at once:
https://github.com/gedw99/runner

**Comment by fengqi** [comment]
Thanks for the reminder. 
The default log path is indeed incorrect. 
This project is still under development, and the overall progress is only about 30%.
